### ISSUE TITLE
Flexible CI

### ISSUE THREAD

**Issue by liemle3893** [flowerinthenight/golang-monorepo#3]
Let's user edit ci file to correct their pipeline.

eg:
```yaml
# .circleci/config.yaml
version: 2.1
jobs:
  build:
    working_directory: /go/src/github.com/liemle3893/golang-monorepo/
    docker:
    - image: golang:1.15
    steps:
    - checkout
    - setup_remote_docker:
        version: 18.06.0-ce
    - run:
        name: build
        shell: /bin/bash
        environment: 
          CI_COMMIT_BEFORE_SHA: << pipeline.git.base_revision >>
          CI_COMMIT_SHA: <<pipeline.git.revision>>
          COMMIT_ID: <<pipeline.git.revision>>
        command: |
          chmod +x ./build.sh
          ./build.sh
```

Where:
```bash
# Extract commit range (or single commit).
COMMIT_RANGE_SEP="..."
if [[ "x$CI_COMMIT_BEFORE_SHA" == "x" ]]; then
  # CI_COMMIT_BEFORE_SHA defined 
  GIT_COMMIT_NUMBER=`git log --oneline | wc -l | bc`
  if [[ $GIT_COMMIT_NUMBER == "1" ]]; then 
    # 4b825dc642cb6eb9a060e54bf8d69288fbee4904 is magic id which is always exists
    CI_COMMIT_BEFORE_SHA="4b825dc642cb6eb9a060e54bf8d69288fbee4904"
    COMMIT_RANGE_SEP=" "
  else
    CI_COMMIT_BEFORE_SHA=`git rev-parse HEAD~1`
  fi
fi
if [[ "x$CI_COMMIT_SHA" == "x" ]]; then
  # CI_COMMIT_SHA is not defined
  CI_COMMIT_SHA=`git rev-parse HEAD`
fi

COMMIT_RANGE="${CI_COMMIT_BEFORE_SHA}${COMMIT_RANGE_SEP}${CI_COMMIT_SHA}"
```

This way, I can flexible using Gitlab or Circle CI as my choice.

**Note**: This also solve the problem when repo only have 1 commit.
